version: "3.8"

services:
  mongo:
    image: mongo:6
    command: ["mongod", "--quiet", "--bind_ip_all"]
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      - MONGO_URI=mongodb://mongo:27017/movie-journal
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend

volumes:
  mongo-data:
